### ISSUE TITLE
Using eosjs2 in IE11 and got ReferenceError: 'TextEncoder' is undefined

### ISSUE THREAD

**Issue by sytong** [EOSIO/eosjs2#56] opened 2018-09-06 10:05 UTC
I tried to use eosjs2 in IE11 and got this error:

**ReferenceError: 'TextEncoder' is undefined**

I notice that `TextEncoder` is an experimental feature in JavaScript is currently not supported in Internet Explorer. Do you have any suggestion about this?

Reference:
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#Browser_compatibility

**Comment by tbfleming** [comment] 2018-09-06 10:49
Does this polyfill work on IE11? https://github.com/inexorabletash/text-encoding/blob/master/README.md

**Comment by chris-allnutt** [comment] 2018-09-06 13:53
It's experimental in IE not Javascript It looks like IE is the minority in support of TextEncoder https://caniuse.com/#search=TextEncoder . I've seen the above polyfill referenced by others as a workaround.  Is there a reason why you need to specifically need to support IE?

**Comment by ChristianDunst** [comment] 2018-09-07 02:37
Is there a reason why you need to specifically need to support IE?

According to: 
<img width="856" alt="screen shot 2018-09-07 at 10 35 11 am" src="https://user-images.githubusercontent.com/14068265/45195372-c7f84380-b289-11e8-9282-71f5b8ca32dd.png">
IE is the second most used browser. I cannot come up with a reason why we would even think of not supporting it.

**Comment by sytong** [comment] 2018-09-07 03:05
> It's experimental in IE not Javascript It looks like IE is the minority in support of TextEncoder https://caniuse.com/#search=TextEncoder .

By the definition of [Experimental Technology](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Conventions_definitions#Experimental) in the MDN Web Docs, TextEncoder is considered `experimental` because of either reason:

1.  It is implemented and enabled by default in less than two modern major browsers.
1.  Its defining spec is not stable and likely to change significantly. Its syntax and behavior is therefore subject to change in future versions of browsers as the specification changes.

**Comment by chris-allnutt** [comment] 2018-09-07 13:05
@sytong did the polyfill work for you?  

I'm not going to argue semantics; or how broadly used IE is.  Ultimately this library is dependent on TextEncoder and will not operate without it.

If the polyfill does work we'll update our documentation to inform developers in need of IE support that it is an option.

**Comment by chris-allnutt** [comment] 2018-09-17 21:29
@sytong @ChristianDunst Re-opening this FYI.  I've done some initial testing and as of eosjs2@0.0.12 you can provide custom encoding and decoding.  I've tested and confirmed the polyfill https://github.com/inexorabletash/text-encoding works in IE11, I'm going to test in Edge and if it works there as well I will update the documentation to aid other developers in the future.

**Comment by chris-allnutt** [comment] 2018-09-18 19:59
@sytong and @ChristianDunst  Resolved in #64 documentation update.  We've verified the polyfill works on IE11 and Edge.

**Closed by chris-allnutt** 2018-09-18 19:59 UTC

**Comment by terrylks** [comment] 2018-10-09 10:51
I have added the `text-encoding` polyfill. It works on both IE11 and Edge.

**However**, there is an another issue with IE11.

In /src/ripemd.js, `Proxy` is used and IE11 is not supporting `Proxy` and it cannot be polyfilled.

So eosjs now is **NOT** working on IE11.

**Comment by chris-allnutt** [comment] 2018-10-09 14:31
@terrylks can you please share the code you're using?  When I used our reference project I had no issues using the reference containers provided by Microsoft for signing transactions.  Is this something other than transaction signing?

Thanks!

**Comment by chris-allnutt** [comment] 2018-10-09 18:00
@terrylks it would also be helpful if this could be opened under a new issue.  This was related to TextEncoder, please include the detailed error message and sample code to help reproduce.
